### ISSUE TITLE
Include screenshots?

### ISSUE THREAD

**Issue by itsrachelfish** [lily-fyi/pymojihash#1]
Heya can you also include screenshots of what this is supposed to look like for people who don't have emoji support in their browsers?

Thanks!!
![screenshot from 2018-05-15 18-29-15](https://user-images.githubusercontent.com/1670549/40090258-f5d8dca4-586d-11e8-94db-8655b9985a33.png)

**Comment by kawa-kokosowa** [comment]
Whaoh @itsrachelfish that's a great idea! I should also link to bubblebbs.cafe!

Thanks for making an issue!

**Comment by kawa-kokosowa** [comment]
Resolved in https://github.com/lily-fyi/pymojihash/commit/c302fb5eda220f548d126a3715bfeac512a2c0c4
